// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_fixed
Eigen::MatrixXd update_fixed(Eigen::MatrixXd X, Rcpp::IntegerVector columns, Eigen::VectorXd lambda_update);
RcppExport SEXP _galamm_update_fixed(SEXP XSEXP, SEXP columnsSEXP, SEXP lambda_updateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type columns(columnsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda_update(lambda_updateSEXP);
    rcpp_result_gen = Rcpp::wrap(update_fixed(X, columns, lambda_update));
    return rcpp_result_gen;
END_RCPP
}
// update_random
Eigen::SparseMatrix<double> update_random(Eigen::SparseMatrix<double> Zt, Eigen::VectorXd lambda_update);
RcppExport SEXP _galamm_update_random(SEXP ZtSEXP, SEXP lambda_updateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type Zt(ZtSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type lambda_update(lambda_updateSEXP);
    rcpp_result_gen = Rcpp::wrap(update_random(Zt, lambda_update));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_galamm_update_fixed", (DL_FUNC) &_galamm_update_fixed, 3},
    {"_galamm_update_random", (DL_FUNC) &_galamm_update_random, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_galamm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
