#' Example dataset with three measurements of a single latent response variable.
#'
#' The dataframe contains 300 observations of the following variables, for a total of
#' 100 subjects:
##' \itemize{
##'  \item{\code{id}: }{Subject ID, 1-100.}
##'  \item{\code{item}: }{Item measured, 1-3.}
##'  \item{\code{y}: }{Value of the measured response.}
##'  \item{\code{x}: }{Predictor variable.}
##' }
#' The underlying smooth curve for the latent trait has been generated by
#' \code{mgcv::gamSim}.
#'
"dat1"
