# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_galamm <- function(y0, X0, Zt0, Lambdat0, Lind) {
    .Call(`_galamm_compute_galamm`, y0, X0, Zt0, Lambdat0, Lind)
}

