# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_galamm <- function(y, X, Zt, Lambdat, Lind, theta, maxit_outer, family) {
    .Call(`_galamm_compute_galamm`, y, X, Zt, Lambdat, Lind, theta, maxit_outer, family)
}

