# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update fixed effect model matrix when loadings have changed
#'
#' @param X                 model matrix
#' @param columns           integer vector of columns to update
#' @param lambda_update     double vector of values with which to multiply old
#'                          values. One for each row of \code{X}.
#' @export
#'
#' @return A matrix in which all columns specified in the
#'  \code{columns} argument have been divided by the values in
#'  \code{lambda_update}.
#'
update_fixed <- function(X, columns, lambda_update) {
    .Call(`_galamm_update_fixed`, X, columns, lambda_update)
}

#' Update random effect model matrix when loadings have changed
#'
#' @param Zt transposed model matrix in compressed sparse column format
#' @param lambda_update dense vector containing values with which the current
#' nonzero elements of \code{Zt} should be multiplied.
#'
#' @export
#'
#' @return A matrix having the same dimension and sparsity pattern as
#' \code{Zt}, but with its nonzero values updated.
#'
update_random <- function(Zt, lambda_update) {
    .Call(`_galamm_update_random`, Zt, lambda_update)
}

